homepage: "https://github.com/lrlt11/libxml2"
language: c++
primary_contact: "wellnhofer@aevum.de"
vendor_ccs:
  - "ddkilzer@apple.com"
  - "benl@google.com"
  - "product-security@apple.com"
  - "dkishore@apple.com"
  - "phan@apple.com"
  - "lglovin@apple.com"
  - "ebanniettis@apple.com"
  - "jm.park@apple.com"
  - "james_e_kim@apple.com"
  - "rding23@apple.com"
  - "albassam@apple.com"
  - "zakr@apple.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - afl
main_repo: 'https://github.com/lrlt11/libxml2.git'
